DROP TABLE IF EXISTS Drivers_Table;
 
CREATE TABLE Drivers_Table (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  phone_number VARCHAR(250) DEFAULT NULL,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL

);